import { schemas, type MenuItem } from '@repo/api-client'
import { centsToDollarInput, dollarInputToCents } from '@repo/shared'
import { useForm, useStore } from '@tanstack/react-form'
import { useEffect, useState } from 'react'
import type { z } from 'zod'

/**
 * Derived from the generated `MenuItem`, not redeclared: the form edits the
 * fields the API accepts, and a renamed column breaks the build here.
 */
export type EditableItem = Pick<
  MenuItem,
  'id' | 'name' | 'categoryId' | 'description' | 'priceCents' | 'isAvailable'
>

/** The body the contract accepts, so the form's values *are* the request. */
export type MenuItemBody = z.infer<typeof schemas.CreateMenuItemBody>

/**
 * Structural validators read badly to a human: an unchosen category fails
 * `zod.uuid()` and Zod says "Invalid UUID", which is true and useless. Only
 * these two are rephrased — every other message is the generated one, so a
 * constraint added to the Drizzle schema surfaces here without code changes.
 */
const FRIENDLY: Partial<Record<keyof MenuItemBody, string>> = {
  categoryId: 'Choose a category',
  priceCents: 'Enter a price',
}

const emptyValues = (item: EditableItem | null): MenuItemBody => ({
  name: item?.name ?? '',
  categoryId: item?.categoryId ?? '',
  description: item?.description ?? null,
  priceCents: item?.priceCents ?? Number.NaN,
  isAvailable: item?.isAvailable ?? true,
})

/**
 * Owns the menu item form: values, validation and the money boundary. The modal
 * that renders it holds no state and computes nothing.
 *
 * Validation is `schemas.CreateMenuItemBody` — generated by Orval from the same
 * OpenAPI document as the hooks, which was generated from the Drizzle schema.
 * The rule that a name is required is written once, in the column definition.
 */
export function useMenuItemForm({
  item,
  onSubmit,
}: {
  item: EditableItem | null
  onSubmit: (body: MenuItemBody) => Promise<unknown>
}) {
  // The text the user is typing. Cents cannot hold "8." mid-keystroke, so the
  // string is the input's state and `priceCents` is what it parses to.
  const [priceInput, setPriceInputState] = useState(item ? centsToDollarInput(item.priceCents) : '')

  const form = useForm({
    defaultValues: emptyValues(item),
    validators: {
      // `onSubmit` rather than `onChange`: errors on a field the user has not
      // finished typing are noise. The generated schema is the whole rule set.
      onSubmit: schemas.CreateMenuItemBody,
    },
    onSubmit: async ({ value }) => {
      await onSubmit({
        ...value,
        name: value.name.trim(),
        description: value.description?.trim() || null,
      })
    },
  })

  const setPriceInput = (next: string) => {
    setPriceInputState(next)
    // NaN when unparseable, so the generated `zod.int().min(0)` rejects it and
    // an empty price cannot reach the server as a free item.
    form.setFieldValue('priceCents', dollarInputToCents(next) ?? Number.NaN)
  }

  // Reopening the modal on a different item must not show the previous edit.
  useEffect(() => {
    form.reset(emptyValues(item))
    setPriceInputState(item ? centsToDollarInput(item.priceCents) : '')
    // eslint-disable-next-line react-hooks/exhaustive-deps -- `form` is stable
  }, [item])

  // `useStore`, not `form.state`: the latter reads the store without
  // subscribing, so a validation failure would update the form and never
  // re-render the modal showing it.
  const fieldMeta = useStore(form.store, (state) => state.fieldMeta)

  // A form-level schema validator reports per *field*: TanStack Form walks each
  // issue's `path` and files it under that field's meta.
  const fieldErrors = Object.fromEntries(
    Object.entries(fieldMeta)
      .map(([field, meta]) => {
        const first = (meta.errors as { message?: string }[] | undefined)?.[0]
        if (!first) return null
        return [field, FRIENDLY[field as keyof MenuItemBody] ?? first.message]
      })
      .filter((entry) => entry !== null),
  ) as Partial<Record<keyof MenuItemBody, string>>

  return { form, priceInput, setPriceInput, fieldErrors }
}
